server:
  port: 6969

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tripPlanner
    username: travel-admin
    password: roadroller
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sp92535@gmail.com
    password: mjeb atga xula sogm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true